language: node_js
node_js:
  - 'stable'
addons:
  apt:
    packages:
      - libnss3
sudo: required
services:
  - xvfb
cache:
  directories:
    - exam_2/node_modules
script:
  # - npm run lint
  - npm run test
  - npm run build
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  on:
    branch:
      - master
      - devel
      - exam_2
